### ISSUE TITLE
Image is not retreving in preview page.

### ISSUE THREAD

**Issue by Inspire123456** [ElijahGlover/Umbraco-S3-Provider#13]
when i am uploading the image in media file its saving in s3 storage .its fine .if  i use that image in my umbraco page and running locally.its not loading the image

![screenshot002](https://user-images.githubusercontent.com/29061212/26868343-54ad39dc-4b86-11e7-9f6a-82526f7dca78.jpg)

**Comment by ElijahGlover** [comment]
Please read the comprehensive readme and check that the virtual path provider is configured correctly.

**Comment by Inspire123456** [comment]
can you tell me the how can i save the images in S3 those are already existed in my umbraco Project of media folder.

**Comment by ElijahGlover** [comment]
You'll need to use a tool like Cloudberry to upload existing files to S3
https://www.cloudberrylab.com/explorer/amazon-s3.aspx
