### ISSUE TITLE
Url issue

### ISSUE THREAD

**Issue by NaiduGiridhar12334** [ElijahGlover/Umbraco-S3-Provider#14]
if i see my media url path in inspect it showing my url with subfolder like this http://goairstage.inspire.technology/services/priority-check-in/ 

how can i change my url into http://mybucketname/services/priority-check-in/

**Comment by ElijahGlover** [comment]
This doesn't have anything to do with the S3 provider. Please reframe your issue so it can actually be solved. our.umbraco.org is a better place to ask questions like this.
