### ISSUE TITLE
Unable to store media

### ISSUE THREAD

**Issue by basemj** [ElijahGlover/Umbraco-S3-Provider#2]
I have been having an issue with creating media content.

I get a 500 response from *"/umbraco/backoffice/UmbracoApi/Media/PostAddFile?origin=blueimp"*

I can see this in the response;
```javascript
)]}',
{
"Message":"An error has occurred.",
"ExceptionMessage":"Object reference not set to an instance of an object.",
"ExceptionType":"System.NullReferenceException",
"StackTrace":"   at Umbraco.Web.WebApi.Filters.FileUploadCleanupFilterAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.CallOnActionExecuted(HttpActionContext actionContext, HttpResponseMessage response, Exception exception)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<>c__DisplayClass2.<System.Web.Http.Filters.IActionFilter.ExecuteActionFilterAsync>b__1(CatchInfo`1 info)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<>c__DisplayClass4`1.<Catch>b__3()\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<>c__DisplayClass9`1.<CatchImplContinuation>b__8(Object state)"
}
```

For the time being, I am putting the AWS keys in the web.config.

I can confirm that changing FileSystemProviders.config back to default, images are saved to file but that could be irrelevant. 

Any ideas what might be going wrong here?

Thanks

Basem

**Comment by basemj** [comment]
My problem was that in the FileSystemProviders.config file I had the wrong values for "bucketHostName" and "region".

The bucketHostName is the S3 website format

**Comment by ElijahGlover** [comment]
Thanks Basem,

I think the provider should give a better description than a very generic
Object null reference. I'll modify when I get a chance or will accept pull
requests.

On Fri, Aug 21, 2015 at 1:31 AM, basemj <notifications@github.com> wrote:

> My problem was that in the FileSystemProviders.config file I had the wrong
> values for "bucketHostName" and "region".
>
> The bucketHostName is the S3 website format
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ElijahGlover/Umbraco-S3-Provider/issues/2#issuecomment-133052343>
> .
>



-- 
*Elijah Glover*
Tel: 0400 770 980
