### ISSUE TITLE
Allow configuration of S3 Canned ACL

### ISSUE THREAD

**Issue by aaronperkins** [ElijahGlover/Umbraco-S3-Provider#21]
Not really an issue but more of a nice to have.

Would be nice to allow configuration of the ACL applied to newly added files. Currently it's hard-coded to public and when using virtual path providers it would be nice to have it set to private.

**Comment by toxster** [comment]
+1

**Comment by ElijahGlover** [comment]
Merged NuGet Package Umbraco.Storage.S3.1.0.33
