### ISSUE TITLE
Delete single image in Umbraco can delete multiple S3 images 

### ISSUE THREAD

**Issue by Mark320** [ElijahGlover/Umbraco-S3-Provider#22]
If you delete an image with a 4 digit media link id in a environment where you also have 5 digit media ids then the 5 digit media items can be deleted as well. 

If any 5 digit media link ids start with the 4 digit media link id then they are also removed. 

For example I delete image with media link id of 1001.
In AWS folder /1001/ and all contents below it is deleted (thumbnails, etc)
But also deleted is folder /10011/, /10015/, etc.

This is a significant flaw and can (and has) lead to a vast amount of images being incorrectly deleted.

**Comment by ElijahGlover** [comment]
Please don't assign blame without doing your homework. In this case, I think you are on the money and there is a problem with deletion not appending slash directory marker meaning S3 listing are pulling back too many files to delete.

What you are seeing is a regression on a pull request merged in Oct 2017.

**Comment by PhilA1** [comment]
Probably my fault sorry. As you have proven you'd need a very specific test case to cover that, maybe a new test should be added.
This is open source to make your life easier, you shouldn't assume it just works all of the time in every case. You should still do your own testing if you are using this for production.

**Comment by Mark320** [comment]
The point of raising this issue or the phrasing was not to assign blame or to attack an open source project for a problem, but was to make sure that the believed significance of the problem was highlighted, so that others would not be affected in the future. Thanks for the quick fix.

**Comment by ElijahGlover** [comment]
All good, please let us know how you go and I'll close this issue.

**Comment by ElijahGlover** [comment]
Closing this issue out, has been resolved for 12 months without comment.
