### ISSUE TITLE
ImageProcessor not working

### ISSUE THREAD

**Issue by afvadillo** [ElijahGlover/Umbraco-S3-Provider#23]
Hi,

I have followed all the instructions. The S3 provider works perfect with Virtual Path but I cannot make it work with ImageProcessor. 

I added the following code to security.config:

`<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="https://<my_bucket>.amazonaws.com/media/"/>
      </settings>
    </service>
  </services>
</security>`

The bucket is public so it should have permissions. The image is uploaded correctly but when I try to resize nothing happens.

Please, could anyone help with this?

Thank you in advance.
Kind Regards.

**Comment by PhilA1** [comment]
You'll need to prove that the public access is working correctly.
The only difference here compared to what we use is, we set the "Host" to a cloudfront url.
E.G. value="https://cms-cdn.mysite.com/media/"

**Comment by afvadillo** [comment]
Thank you for your response.

Do you have the cloudfront url only in security.config or also in FileSystemProvider.config?

Regards.

**Comment by PhilA1** [comment]
just security.config

**Comment by afvadillo** [comment]
I tried this but still not working:

`<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://d2y0zut8h2zbex.cloudfront.net/media/"/>
      </settings>
    </service>
  </services>
</security>`

Also checked the public access to the S3 bucket and it's fine.

**Comment by PhilA1** [comment]
so you can view an image in your browser using the cloudfront or the s3 path?
E.G
http://d2y0zut8h2zbex.cloudfront.net/media/1001/facebook.png ??

Note: does https work?

**Comment by afvadillo** [comment]
Yes this works just fine:

https://d2y0zut8h2zbex.cloudfront.net/media/4316487/whatsapp-image-2018-04-03-at-094654-1.jpeg

I should probably have mentioned that the image is still being shown, but not resized:

This is the tag generated:

<img class="br5 croppedImg" src="/media/4316488/whatsapp-image-2018-04-03-at-094654-1.jpeg?anchor=center&amp;mode=crop&amp;width=300&amp;height=200&amp;rnd=131672422100000000">

**Comment by davidmcdtew** [comment]
I am having the same issue with images not cropping on the site. The image loads as if there is no crop specified, I always receive the full image.

Any ideas?

**Comment by afvadillo** [comment]
I actually fixed by myself.

You have to add the references to imageprocessor config files in your web.config. Those are probably missing.

<sectionGroup name="imageProcessor">
      <section name="security" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageSecuritySection, ImageProcessor.Web" />
      <section name="processing" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageProcessingSection, ImageProcessor.Web" />
      <section name="caching" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageCacheSection, ImageProcessor.Web" />
    </sectionGroup>

**Comment by davidmcdtew** [comment]
I do actually have this in the web.config already

<sectionGroup name="imageProcessor">
      <section name="security" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageSecuritySection, ImageProcessor.Web" />
      <section name="processing" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageProcessingSection, ImageProcessor.Web" />
      <section name="caching" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageCacheSection, ImageProcessor.Web" />
    </sectionGroup>

**Comment by davidmcdtew** [comment]
Turns out it is only previously uploaded images that are not cropping, new images crop fine, is there some stored in the database for cropping like a url / flag which with the new upload as its aware of s3 at the time of upload?

**Comment by davidmcdtew** [comment]
have managed to resolve the issue, there were bucket permission issues cached.
The only remaining issue is with non-image media files like audio files, I can access them through the bucket url but not through the relative url from the site. i.e. /media/1009/test.mp3

**Comment by davidmcdtew** [comment]
So we have resolved this issue with loading the media files, a missing config got stripped out of our build for the media folder.
One thing we did come across and I know its probably off topic for this thread is we allow seeking on our audio files and the VPP does not appear to be able to handle 206 partial content requests

**Comment by dozkaya** [comment]
@davidmcdtew How did you solve the issue about urls? Even media files, I can access them through the bucket url but not through the relative url from the site. i.e. /media/1009/test.mp3.
