### ISSUE TITLE
Question about Umbraco Courier

### ISSUE THREAD

**Issue by warrencohaesus** [ElijahGlover/Umbraco-S3-Provider#24]
Hi,

I'm wondering if the S3 Provider is known to work (anywhere) with Umbraco Courier? https://umbraco.com/products/umbraco-courier/

Regards,

Warren.

**Comment by ElijahGlover** [comment]
@warrencohaesus It should work as expected as it uses the standard Umbraco interface/hooks. Umbraco Courier is a strange beast so if you run into trouble post your findings.
