### ISSUE TITLE
Rendering image in backoffice not working

### ISSUE THREAD

**Issue by dozkaya** [ElijahGlover/Umbraco-S3-Provider#27]
Hi,
I have followed all the instructions and using Umbraco 7.12.2 and I configured all the settings for Virtual Path Provider with ImageProcessor. When I upload an image in backoffice I can see the thumbnail and it is uploaded properly in bucket. But when I click on the image that gives 404 error. I can access it though the bucket url and the relative url from the site with querystring i.e. /media/1000/test.jpg?width=1000, but not without querystring. 
Please, could anyone help with this?
Thank you.

**Comment by PhilA1** [comment]
have you configured the FileSystemProviders.config file properly?

E.G
<FileSystemProviders>
  <Provider alias="media" type="Umbraco.Storage.S3.BucketFileSystem, Umbraco.Storage.S3">
    <Parameters>
      
      <add key="bucketName" value="my_bucket_name" />
      
      <add key="bucketHostName" value="" />
      
      <add key="bucketKeyPrefix" value="media" />
      
      <add key="region" value="eu-west-1" />
    </Parameters>
  </Provider>

**Comment by dozkaya** [comment]
Hi, I solved the issue. Global.asax was not set-up correctly that was inherits Umbraco.Web.UmbracoApplication as default. When I set it up correctly that worked. 

Thanks
