### ISSUE TITLE
Can't get Virtual Path Provider to work

### ISSUE THREAD

**Issue by bjammin** [ElijahGlover/Umbraco-S3-Provider#4]
Thanks for this component!

I have installed your provider and configured as per the instructions.  However the StaticFileHandler doesn't seem to be firing at all.  I just get a 404 error for any files in the /Media folder.

I'm running locally using VS 2015 and IISExpress.

Is there anything else that has to be configured?

edit: I've also tried using full IIS 8 locally

**Comment by ElijahGlover** [comment]
Hi bjammin,

IIS8 and IISExpress should work the same. Verify AWS access keys and secrets, 404's may indicate no object exists at that location. Use a tool like fiddler to inspect requests going to the upstream API endpoint.

Cheers,
Elijah
