### ISSUE TITLE
Cannot serve file locally if "bucketKeyPrefix" is changed from "media"

### ISSUE THREAD

**Issue by nicgordon** [ElijahGlover/Umbraco-S3-Provider#5]
Firstly thank you for making this plugin, it is very convenient to be able to save our media directly to an S3 bucket without much hassle at all! 

I've noticed what is perhaps a bug whereby when you update the `bucketKeyPrefix` setting inside `~/Config/FileSystemProviders.config`, Umbraco is unable to find the image for rendering inside the backoffice. 

To replicate: 
- Update value of `bucketKeyPrefix` to `media_123`
- Restart server etc
- Upload some media. It will land in the correct S3 bucket
- Note that the CMS will not be able to find the image as the path it is trying to find it in is `http://localhost:53714/media_123/1001/test.jpg`

I have also tried calling `FileSystemVirtualPathProvider.ConfigureMedia("media_123");` inside `Global.asax.cs` to no avail. Is this a problem with the `VirtualPathProvider` or is there just some configuration that I have overlooked when updating this setting?

**Comment by ElijahGlover** [comment]
Hi Nic

As the VirtualPath provider is an ASP.NET concept you will need to ensure the request is hitting the ASP.NET pipeline. Ensure this directory is served by the StaticFileHandler (Documented in the read me)
