### ISSUE TITLE
404 on non image media

### ISSUE THREAD

**Issue by lordy1981** [ElijahGlover/Umbraco-S3-Provider#7]
Hi,

I've been using this for a while along side image processor and it has been working really well. I recently upgraded a site to Umbraco 7.5.3, and I now have an issue where NON image media throws a 404 (PDs, XLS, DOC etc.)

I am not sure what the issue is, whether it's Image Processor intercepting the request (assume it would only intercept image requests), or something new with Umbraco 7.5, but I am pulling my hair out. I had to set Image Processor to "InterceptAllRequests", otherwise images were not being rendered without querystring paramters (therefore not appearing properly in the Umbraco media section), turning this off makes no difference to the issue I am having with non image files.

I have followed the setup documented in the readme file, there is a new web config in the media folder for this version of Umbraco, and i've tried adding the StaticFileHandler into that, but no joy.

Help :-)

**Comment by ElijahGlover** [comment]
Please provide more information or provide a pull request. I have not tested this plugin with Umbraco 7.5.3.

**Comment by lordy1981** [comment]
Looking at fiddler, the requests for any media (other than images) is not being sent onto to S3. If I place the file in question physically inside the media folder on the web server, then the media is served, so for whatever reason the request isn't being served by the VPP, and IIS is throwing a 404 as the media doesn't physically exist. This was working on previous verison of Umbraco 7.4.3, so I am assuming that something has changed in the config, but can't work out what?

**Comment by lordy1981** [comment]
OK found the issue, the Umbraco upgrade overwrote my global.asax, which and the markup was inheriting from Umbraco.Web.UmbracoApplication, therefore my OnApplicationStarting method was not being hit, where I register the VPP.....! Doh, one to watch out for in future for me!!

**Comment by ElijahGlover** [comment]
Thanks @lordy1981
